# Generated by Django 6.0.2 on 2026-07-29 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0002_alter_leaverequest_status_leaveapprovalhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='leave_documents/'),
        ),
    ]
