# Generated by Django 6.0.2 on 2026-07-18 06:28

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Branches',
                'db_table': 'branches',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'departments',
            },
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'designations',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('codename', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'permissions',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ADMIN', 'Admin'), ('HR', 'HR'), ('MANAGER', 'Manager'), ('EMPLOYEE', 'Employee')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_id', models.CharField(help_text='Employee ID for login', max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('permissions', models.ManyToManyField(blank=True, related_name='users', to='accounts.permission')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.role')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='employee_photos/')),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHERS', 'Others')], max_length=10)),
                ('date_of_joining', models.DateField()),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('O+', 'O+'), ('B+', 'B+'), ('AB+', 'AB+'), ('A-', 'A-'), ('O-', 'O-'), ('B-', 'B-'), ('AB-', 'AB-')], max_length=5)),
                ('marital_status', models.CharField(choices=[('MARRIED', 'Married'), ('UNMARRIED', 'Unmarried')], max_length=15)),
                ('official_email', models.EmailField(blank=True, max_length=254)),
                ('contact_number', models.CharField(max_length=15)),
                ('another_contact_number', models.CharField(blank=True, max_length=15)),
                ('pan_number', models.CharField(blank=True, max_length=10)),
                ('uid_number', models.CharField(blank=True, help_text='Aadhaar Number', max_length=12)),
                ('una_number', models.CharField(blank=True, max_length=50)),
                ('esic_number', models.CharField(blank=True, max_length=50)),
                ('pf_number', models.CharField(blank=True, max_length=50)),
                ('qualification', models.CharField(choices=[('ILLITERATE', 'Illiterate'), ('NON-METRIC', 'Non-Metric'), ('METRIC', 'Metric'), ('SENIOR-SECONDARY', 'Senior-Secondary'), ('GRADUATE', 'Graduate'), ('POST-GRADUATE', 'Post-Graduate'), ('TECHNICAL(PROFESSIONAL)', 'Technical(Professional)'), ('DOCTORATE', 'Doctorate'), ('DIPLOMA', 'Diploma'), ('OTHERS', 'Others'), ('MBA', 'MBA')], max_length=50)),
                ('present_address', models.TextField()),
                ('present_city', models.CharField(max_length=100)),
                ('present_state', models.CharField(choices=[('ANDHRAPRADESH', 'Andhra Pradesh'), ('ARUNACHALPRADESH', 'Arunachal Pradesh'), ('ASSAM', 'Assam'), ('BIHAR', 'Bihar'), ('CHHATTISGARH', 'Chhattisgarh'), ('DELHI', 'Delhi'), ('GOA', 'Goa'), ('GUJARAT', 'Gujarat'), ('HARYANA', 'Haryana'), ('HIMACHALPRADESH', 'Himachal Pradesh'), ('JHARKHAND', 'Jharkhand'), ('KARNATAKA', 'Karnataka'), ('KERALA', 'Kerala'), ('MADHYAPRADESH', 'Madhya Pradesh'), ('MAHARASHTRA', 'Maharashtra'), ('MANIPUR', 'Manipur'), ('MEGHALAYA', 'Meghalaya'), ('MIZORAM', 'Mizoram'), ('NAGALAND', 'Nagaland'), ('ODISHA', 'Odisha'), ('PUNJAB', 'Punjab'), ('RAJASTHAN', 'Rajasthan'), ('SIKKIM', 'Sikkim'), ('TAMILNADU', 'Tamil Nadu'), ('TELANGANA', 'Telangana'), ('TRIPURA', 'Tripura'), ('UTTARAKHAND', 'Uttarakhand'), ('UTTARPRADESH', 'Uttar Pradesh'), ('WESTBENGAL', 'West Bengal')], max_length=50)),
                ('present_pincode', models.CharField(max_length=6)),
                ('same_as_present_address', models.BooleanField(default=False)),
                ('permanent_address', models.TextField()),
                ('permanent_city', models.CharField(max_length=100)),
                ('permanent_state', models.CharField(choices=[('ANDHRAPRADESH', 'Andhra Pradesh'), ('ARUNACHALPRADESH', 'Arunachal Pradesh'), ('ASSAM', 'Assam'), ('BIHAR', 'Bihar'), ('CHHATTISGARH', 'Chhattisgarh'), ('DELHI', 'Delhi'), ('GOA', 'Goa'), ('GUJARAT', 'Gujarat'), ('HARYANA', 'Haryana'), ('HIMACHALPRADESH', 'Himachal Pradesh'), ('JHARKHAND', 'Jharkhand'), ('KARNATAKA', 'Karnataka'), ('KERALA', 'Kerala'), ('MADHYAPRADESH', 'Madhya Pradesh'), ('MAHARASHTRA', 'Maharashtra'), ('MANIPUR', 'Manipur'), ('MEGHALAYA', 'Meghalaya'), ('MIZORAM', 'Mizoram'), ('NAGALAND', 'Nagaland'), ('ODISHA', 'Odisha'), ('PUNJAB', 'Punjab'), ('RAJASTHAN', 'Rajasthan'), ('SIKKIM', 'Sikkim'), ('TAMILNADU', 'Tamil Nadu'), ('TELANGANA', 'Telangana'), ('TRIPURA', 'Tripura'), ('UTTARAKHAND', 'Uttarakhand'), ('UTTARPRADESH', 'Uttar Pradesh'), ('WESTBENGAL', 'West Bengal')], max_length=50)),
                ('permanent_pincode', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employee_profiles',
            },
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('AADHAAR', 'Aadhaar Card'), ('PAN', 'PAN Card'), ('PHOTO', 'Passport Size Photo'), ('RESUME', 'Resume/CV'), ('EDUCATION', 'Educational Certificates'), ('OFFER_LETTER', 'Offer Letter'), ('JOINING_LETTER', 'Joining Letter'), ('BANK_PASSBOOK', 'Bank Passbook/Cancelled Cheque')], max_length=20)),
                ('document_file', models.FileField(upload_to='employee_documents/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.employeeprofile')),
            ],
            options={
                'db_table': 'employee_documents',
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_name', models.CharField(max_length=100)),
                ('relationship_type', models.CharField(choices=[('FATHER', 'Father'), ('MOTHER', 'Mother'), ('SPOUSE', 'Spouse'), ('SIBLING', 'Sibling'), ('OTHERS', 'Others')], max_length=20)),
                ('parent_mobile', models.CharField(max_length=15)),
                ('another_mobile', models.CharField(blank=True, max_length=15)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contact', to='accounts.employeeprofile')),
            ],
            options={
                'db_table': 'emergency_contacts',
            },
        ),
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_branch', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=20)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('is_salary_account', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='accounts.employeeprofile')),
            ],
            options={
                'db_table': 'bank_details',
            },
        ),
        migrations.CreateModel(
            name='EmploymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(blank=True, choices=[('M', 'M'), ('E1-Jaipur', 'E1-Jaipur'), ('M1', 'M1'), ('E2-Jaipur', 'E2-Jaipur'), ('F1', 'F1'), ('F', 'F'), ('E1', 'E1'), ('E', 'E')], max_length=20)),
                ('employment_type', models.CharField(choices=[('PROBATION', 'Probation'), ('TRAINEE', 'Trainee'), ('PERMANENT', 'Permanent'), ('UNDER NOTICE', 'Under Notice')], max_length=20)),
                ('deputed_project', models.CharField(blank=True, choices=[('NAGAR NIGAM JAIPUR HERITAGE', 'Nagar Nigam Jaipur Heritage'), ('UDAIPUR NAGAR NIGAM', 'Udaipur Nagar Nigam'), ('NAGAR NIGAM JAIPUR GREATER', 'Nagar Nigam Jaipur Greater'), ('KOTA NAGAR NIGAM NORTH', 'Kota Nagar Nigam North'), ('KOTA NAGAR NIGAM CHURU', 'Kota Nagar Nigam Churu'), ('MUNICIPAL COUNCIL CHOMU', 'Municipal Council Chomu')], max_length=100)),
                ('effective_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.branch')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.department')),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.designation')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employment_details', to='accounts.employeeprofile')),
                ('reporting_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employment_details',
            },
        ),
        migrations.CreateModel(
            name='PastEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('role_name', models.CharField(blank=True, max_length=50)),
                ('profile_data', models.JSONField(blank=True, null=True)),
                ('emergency_contact_data', models.JSONField(blank=True, null=True)),
                ('employment_data', models.JSONField(blank=True, null=True)),
                ('bank_data', models.JSONField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('deletion_reason', models.TextField(blank=True)),
                ('date_joined', models.DateTimeField(null=True)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('last_working_day', models.DateField(blank=True, null=True)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_employees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'past_employees',
                'ordering': ['-deleted_at'],
            },
        ),
    ]
