# Generated by Django 6.0.2 on 2026-03-06 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Branches',
                'db_table': 'branches',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'departments',
            },
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'designations',
            },
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHERS', 'Others')], max_length=10)),
                ('date_of_joining', models.DateField()),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('O+', 'O+'), ('B+', 'B+'), ('AB+', 'AB+'), ('A-', 'A-'), ('O-', 'O-'), ('B-', 'B-'), ('AB-', 'AB-')], max_length=5)),
                ('marital_status', models.CharField(choices=[('MARRIED', 'Married'), ('UNMARRIED', 'Unmarried')], max_length=15)),
                ('official_email', models.EmailField(blank=True, max_length=254)),
                ('contact_number', models.CharField(max_length=15)),
                ('another_contact_number', models.CharField(blank=True, max_length=15)),
                ('pan_number', models.CharField(blank=True, max_length=10)),
                ('uid_number', models.CharField(blank=True, help_text='Aadhaar Number', max_length=12)),
                ('una_number', models.CharField(blank=True, max_length=50)),
                ('esic_number', models.CharField(blank=True, max_length=50)),
                ('pf_number', models.CharField(blank=True, max_length=50)),
                ('qualification', models.CharField(choices=[('ILLITERATE', 'Illiterate'), ('NON-METRIC', 'Non-Metric'), ('METRIC', 'Metric'), ('SENIOR-SECONDARY', 'Senior-Secondary'), ('GRADUATE', 'Graduate'), ('POST-GRADUATE', 'Post-Graduate'), ('TECHNICAL(PROFESSIONAL)', 'Technical(Professional)'), ('DOCTORATE', 'Doctorate'), ('DIPLOMA', 'Diploma'), ('OTHERS', 'Others'), ('MBA', 'MBA')], max_length=50)),
                ('present_address', models.TextField()),
                ('present_city', models.CharField(max_length=100)),
                ('present_state', models.CharField(choices=[('ANDHRAPRADESH', 'Andhra Pradesh'), ('ARUNACHALPRADESH', 'Arunachal Pradesh'), ('ASSAM', 'Assam'), ('BIHAR', 'Bihar'), ('CHHATTISGARH', 'Chhattisgarh'), ('DELHI', 'Delhi'), ('GOA', 'Goa'), ('GUJARAT', 'Gujarat'), ('HARYANA', 'Haryana'), ('HIMACHALPRADESH', 'Himachal Pradesh'), ('JHARKHAND', 'Jharkhand'), ('KARNATAKA', 'Karnataka'), ('KERALA', 'Kerala'), ('MADHYAPRADESH', 'Madhya Pradesh'), ('MAHARASHTRA', 'Maharashtra'), ('MANIPUR', 'Manipur'), ('MEGHALAYA', 'Meghalaya'), ('MIZORAM', 'Mizoram'), ('NAGALAND', 'Nagaland'), ('ODISHA', 'Odisha'), ('PUNJAB', 'Punjab'), ('RAJASTHAN', 'Rajasthan'), ('SIKKIM', 'Sikkim'), ('TAMILNADU', 'Tamil Nadu'), ('TELANGANA', 'Telangana'), ('TRIPURA', 'Tripura'), ('UTTARAKHAND', 'Uttarakhand'), ('UTTARPRADESH', 'Uttar Pradesh'), ('WESTBENGAL', 'West Bengal')], max_length=50)),
                ('present_pincode', models.CharField(max_length=6)),
                ('same_as_present_address', models.BooleanField(default=False)),
                ('permanent_address', models.TextField()),
                ('permanent_city', models.CharField(max_length=100)),
                ('permanent_state', models.CharField(choices=[('ANDHRAPRADESH', 'Andhra Pradesh'), ('ARUNACHALPRADESH', 'Arunachal Pradesh'), ('ASSAM', 'Assam'), ('BIHAR', 'Bihar'), ('CHHATTISGARH', 'Chhattisgarh'), ('DELHI', 'Delhi'), ('GOA', 'Goa'), ('GUJARAT', 'Gujarat'), ('HARYANA', 'Haryana'), ('HIMACHALPRADESH', 'Himachal Pradesh'), ('JHARKHAND', 'Jharkhand'), ('KARNATAKA', 'Karnataka'), ('KERALA', 'Kerala'), ('MADHYAPRADESH', 'Madhya Pradesh'), ('MAHARASHTRA', 'Maharashtra'), ('MANIPUR', 'Manipur'), ('MEGHALAYA', 'Meghalaya'), ('MIZORAM', 'Mizoram'), ('NAGALAND', 'Nagaland'), ('ODISHA', 'Odisha'), ('PUNJAB', 'Punjab'), ('RAJASTHAN', 'Rajasthan'), ('SIKKIM', 'Sikkim'), ('TAMILNADU', 'Tamil Nadu'), ('TELANGANA', 'Telangana'), ('TRIPURA', 'Tripura'), ('UTTARAKHAND', 'Uttarakhand'), ('UTTARPRADESH', 'Uttar Pradesh'), ('WESTBENGAL', 'West Bengal')], max_length=50)),
                ('permanent_pincode', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employee_profiles',
            },
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('AADHAAR', 'Aadhaar Card'), ('PAN', 'PAN Card'), ('PHOTO', 'Passport Size Photo'), ('RESUME', 'Resume/CV'), ('EDUCATION', 'Educational Certificates'), ('OFFER_LETTER', 'Offer Letter'), ('JOINING_LETTER', 'Joining Letter'), ('BANK_PASSBOOK', 'Bank Passbook/Cancelled Cheque')], max_length=20)),
                ('document_file', models.FileField(upload_to='employee_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.employeeprofile')),
            ],
            options={
                'db_table': 'employee_documents',
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_name', models.CharField(max_length=100)),
                ('relationship_type', models.CharField(choices=[('FATHER', 'Father'), ('MOTHER', 'Mother'), ('SPOUSE', 'Spouse'), ('SIBLING', 'Sibling'), ('OTHERS', 'Others')], max_length=20)),
                ('parent_mobile', models.CharField(max_length=15)),
                ('another_mobile', models.CharField(blank=True, max_length=15)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contact', to='accounts.employeeprofile')),
            ],
            options={
                'db_table': 'emergency_contacts',
            },
        ),
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_branch', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=20)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('is_salary_account', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='accounts.employeeprofile')),
            ],
            options={
                'db_table': 'bank_details',
            },
        ),
        migrations.CreateModel(
            name='EmploymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(blank=True, choices=[('M', 'M'), ('E1-Jaipur', 'E1-Jaipur'), ('M1', 'M1'), ('E2-Jaipur', 'E2-Jaipur'), ('F1', 'F1'), ('F', 'F'), ('E1', 'E1'), ('E', 'E')], max_length=20)),
                ('employment_type', models.CharField(choices=[('PROBATION', 'Probation'), ('TRAINEE', 'Trainee'), ('PERMANENT', 'Permanent'), ('UNDER NOTICE', 'Under Notice')], max_length=20)),
                ('deputed_project', models.CharField(blank=True, choices=[('NAGAR NIGAM JAIPUR HERITAGE', 'Nagar Nigam Jaipur Heritage'), ('UDAIPUR NAGAR NIGAM', 'Udaipur Nagar Nigam'), ('NAGAR NIGAM JAIPUR GREATER', 'Nagar Nigam Jaipur Greater'), ('KOTA NAGAR NIGAM NORTH', 'Kota Nagar Nigam North'), ('KOTA NAGAR NIGAM CHURU', 'Kota Nagar Nigam Churu'), ('MUNICIPAL COUNCIL CHOMU', 'Municipal Council Chomu')], max_length=100)),
                ('effective_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.branch')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.department')),
                ('designation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.designation')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employment_details', to='accounts.employeeprofile')),
                ('reporting_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employment_details',
            },
        ),
    ]
