# Generated by Django 6.0.2 on 2026-07-21 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promoted_date', models.DateField()),
                ('pay_level', models.CharField(max_length=50)),
                ('basic_pay', models.CharField(max_length=50)),
                ('effective_date_from', models.DateField()),
                ('approved_by', models.CharField(max_length=100)),
                ('remark', models.TextField(blank=True, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='promotion_documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='accounts.employeeprofile')),
                ('promoted_designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.designation')),
            ],
            options={
                'db_table': 'employee_promotions',
            },
        ),
    ]
