# Generated by Django 6.0.2 on 2026-07-21 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_promotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Increment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('increment_date', models.DateField()),
                ('increment_type', models.CharField(max_length=50)),
                ('pay_level', models.CharField(max_length=50)),
                ('previous_basic_pay', models.CharField(max_length=50)),
                ('increment_amount', models.CharField(max_length=50)),
                ('new_basic_pay', models.CharField(max_length=50)),
                ('effective_date_from', models.DateField()),
                ('approved_by', models.CharField(max_length=100)),
                ('remark', models.TextField(blank=True, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='increment_documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='increments', to='accounts.employeeprofile')),
            ],
            options={
                'db_table': 'employee_increments',
            },
        ),
    ]
