# Generated by Django 6.0.2 on 2026-03-07 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_managers_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('role_name', models.CharField(blank=True, max_length=50)),
                ('profile_data', models.JSONField(blank=True, null=True)),
                ('emergency_contact_data', models.JSONField(blank=True, null=True)),
                ('employment_data', models.JSONField(blank=True, null=True)),
                ('bank_data', models.JSONField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('deletion_reason', models.TextField(blank=True)),
                ('date_joined', models.DateTimeField(null=True)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('last_working_day', models.DateField(blank=True, null=True)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_employees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'past_employees',
                'ordering': ['-deleted_at'],
            },
        ),
    ]
