# Generated by Django 6.0.2 on 2026-07-22 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_increment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateField()),
                ('present_office', models.CharField(max_length=100)),
                ('new_office', models.CharField(max_length=100)),
                ('present_department', models.CharField(max_length=100)),
                ('new_department', models.CharField(max_length=100)),
                ('present_zone', models.CharField(max_length=100)),
                ('new_zone', models.CharField(max_length=100)),
                ('relieving_date', models.DateField()),
                ('effective_date_from', models.DateField()),
                ('approved_by', models.CharField(max_length=100)),
                ('remark', models.TextField(blank=True, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='transfer_documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='accounts.employeeprofile')),
            ],
            options={
                'db_table': 'employee_transfers',
            },
        ),
    ]
