# Generated by Django 6.0.2 on 2026-07-22 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_transfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='esic_number',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='pan_number',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='pf_number',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='uid_number',
            field=models.CharField(blank=True, help_text='Aadhaar Number', max_length=255),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='una_number',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
