# Generated by Django 6.0.2 on 2026-07-22 08:46

import accounts.encrypted_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_employeeprofile_esic_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='esic_number',
            field=accounts.encrypted_fields.EncryptedCharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='pan_number',
            field=accounts.encrypted_fields.EncryptedCharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='pf_number',
            field=accounts.encrypted_fields.EncryptedCharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='uid_number',
            field=accounts.encrypted_fields.EncryptedCharField(blank=True, help_text='Aadhaar Number', max_length=255),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='una_number',
            field=accounts.encrypted_fields.EncryptedCharField(blank=True, max_length=255),
        ),
    ]
