# Generated by Django 6.0.2 on 2026-03-29 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employmentdetails',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='employmentdetails',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employmentdetails',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='emergencycontact',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='employeedocument',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='employmentdetails',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='employmentdetails',
            name='reporting_officer',
        ),
        migrations.RemoveField(
            model_name='pastemployee',
            name='deleted_by',
        ),
        migrations.DeleteModel(
            name='BankDetails',
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Designation',
        ),
        migrations.DeleteModel(
            name='EmergencyContact',
        ),
        migrations.DeleteModel(
            name='EmployeeDocument',
        ),
        migrations.DeleteModel(
            name='EmployeeProfile',
        ),
        migrations.DeleteModel(
            name='EmploymentDetails',
        ),
        migrations.DeleteModel(
            name='PastEmployee',
        ),
    ]
