# Generated by Django 6.0.2 on 2026-07-23 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_encrypt_existing_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reporting_manager',
            field=models.ForeignKey(blank=True, help_text="Employee's reporting manager", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reporting_employees', to=settings.AUTH_USER_MODEL),
        ),
    ]
