# Generated by Django 6.0.2 on 2026-07-29 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_reporting_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Leave blank for cross-branch department', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='accounts.branch'),
        ),
        migrations.AddField(
            model_name='designation',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Leave blank for cross-branch designation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designations', to='accounts.branch'),
        ),
        migrations.AddField(
            model_name='designation',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Leave blank for cross-department designation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designations', to='accounts.department'),
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='designation',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='designation',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('name', 'branch')},
        ),
        migrations.AlterUniqueTogether(
            name='designation',
            unique_together={('name', 'branch')},
        ),
    ]
