# Generated by Django 6.0.2 on 2026-08-03 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_department_branch_designation_branch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradePayLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Grade label, e.g. E1, E2, M', max_length=50, unique=True)),
                ('min_ctc', models.DecimalField(decimal_places=2, help_text='Minimum monthly CTC (₹)', max_digits=12)),
                ('max_ctc', models.DecimalField(blank=True, decimal_places=2, help_text="Maximum monthly CTC (₹). Leave blank for 'no upper limit' (e.g. E5)", max_digits=12, null=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Grade / Pay Level',
                'verbose_name_plural': 'Grade / Pay Levels',
                'db_table': 'grade_pay_levels',
                'ordering': ['min_ctc'],
            },
        ),
        migrations.AddField(
            model_name='employmentdetails',
            name='grade_level',
            field=models.ForeignKey(blank=True, help_text='Grade / Pay Level from master table', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employment_details', to='accounts.gradepaylevel'),
        ),
    ]
