# Generated by Django 6.0.2 on 2026-08-10 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_update_e1_e2_ranges'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='initial_designation',
            field=models.CharField(blank=True, default='', help_text='Designation held before this promotion (snapshot)', max_length=100),
        ),
    ]
