# Generated by Django 6.0.2 on 2026-03-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='paid_days',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Actual paid days (present + sundays)', max_digits=5),
        ),
    ]
