# Generated by Django 6.0.2 on 2026-08-10 08:02

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarystructure',
            name='basic_salary',
            field=models.DecimalField(decimal_places=2, help_text='50% of Gross Salary (Auto-calculated)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='salarystructure',
            name='cca',
            field=models.DecimalField(decimal_places=2, default=0, help_text='City Compensatory Allowance — balancing component (Auto-calculated)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='salarystructure',
            name='pf_employer',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Employer PF - 12% of basic (Auto-calculated, deducted from CTC)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.CreateModel(
            name='EmployeeTDS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(help_text='e.g., 2026-27', max_length=20)),
                ('effective_date_from', models.DateField(help_text='Start date for TDS deduction')),
                ('effective_date_to', models.DateField(help_text='End date for TDS deduction')),
                ('tds_per_month', models.DecimalField(decimal_places=2, help_text='TDS amount per month', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('tds_per_year', models.DecimalField(decimal_places=2, help_text='TDS amount per year (auto-calculated as tds_per_month * 12)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('remark', models.TextField(blank=True, help_text='Optional remark')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tds_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee TDS',
                'verbose_name_plural': 'Employee TDS Records',
                'db_table': 'employee_tds',
                'ordering': ['-financial_year', '-effective_date_from'],
                'unique_together': {('employee', 'financial_year')},
            },
        ),
    ]
