# Generated by Django 6.0.2 on 2026-08-10 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_alter_salarystructure_basic_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeetds',
            name='effective_date_to',
            field=models.DateField(blank=True, help_text="End date for TDS deduction (leave blank for 'Effective Until Changed')", null=True),
        ),
    ]
