# Generated by Django 6.0.2 on 2026-08-10 08:47

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_alter_employeetds_effective_date_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='tds',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tax Deducted at Source (TDS)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='salary',
            name='total_deductions',
            field=models.DecimalField(decimal_places=2, help_text='Total employee deductions (PF + ESI + TDS + Other)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
