# Generated by Django 6.0.2 on 2026-08-10 09:04

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_salary_tds_alter_salary_total_deductions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarystructure',
            name='esi_employee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Employee ESI - 0.75% of gross (if monthly CTC <= 22000)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='salarystructure',
            name='esi_employer',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Employer ESI - 3.25% of gross (if monthly CTC <= 22000)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
