# Generated by Django 6.0.2 on 2026-08-10 09:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_alter_salarystructure_esi_employee_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='ineligibility_reason',
            field=models.TextField(blank=True, help_text='Reason for payroll ineligibility'),
        ),
        migrations.AddField(
            model_name='salary',
            name='is_eligible',
            field=models.BooleanField(default=True, help_text='Whether employee is eligible for payroll generation based on worked days'),
        ),
        migrations.AddField(
            model_name='salary',
            name='minimum_required_days',
            field=models.IntegerField(default=6, help_text='Minimum qualifying worked days required for payroll eligibility (from settings)'),
        ),
        migrations.AddField(
            model_name='salary',
            name='worked_days',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Qualifying worked days (PRESENT + HALF_DAY attendance, excluding Sundays/weekly-offs/holidays)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='salary',
            name='paid_days',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Payable days (present + sundays + paid leaves) for salary calculation', max_digits=5),
        ),
        migrations.AlterField(
            model_name='salary',
            name='status',
            field=models.CharField(choices=[('GENERATED', 'Generated'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled'), ('NOT_ELIGIBLE', 'Not Eligible')], default='GENERATED', max_length=20),
        ),
        migrations.CreateModel(
            name='PayrollSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_days_for_payroll', models.IntegerField(default=6, help_text='Minimum qualifying worked days required for payroll generation eligibility (excludes Sundays/weekly-offs)', validators=[django.core.validators.MinValueValidator(0)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payroll Settings',
                'verbose_name_plural': 'Payroll Settings',
                'db_table': 'payroll_settings',
            },
        ),
    ]
